version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  

  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build React App
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:oXdNTQu+3Ip+GvuorqLi06FWWJdJMG+5nn4rcCZ+WMY"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@54.88.72.192 << 'EOF'
              cd /home/ubuntu/react-app
              git pull origin main
              npm install
              npm run build
              pm2 restart all || pm2 start npm --name "react-app" -- start
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build
